  node:
    container_name: node
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./:/var/www/node
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    tty: true