  node:
    container_name: node
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./pod:/var/www/node/pod
      - ./src:/var/www/node/src
    restart: unless-stopped
    networks:
      - arnelify-network
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    tty: true