  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_PASS}
      - MYSQL_DATABASE=${MYSQL_MASTER_NAME}
    volumes:
      - ./docker/mysql/data/:/var/lib/mysql/
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
  pma:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=mysql
      # - PMA_USER=${MYSQL_MASTER_USER}
      # - PMA_PASSWORD=${MYSQL_MASTER_PASS}
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    depends_on:
      - mysql